#!/bin/bash


VOLUME=$(pactl list sink-inputs |grep -B18 Spotify |awk '/Volume/ {print $5}' |sed 's/%//')
# check command line arguments first

 
 
# go through each line of the sink-inputs output
pactl list sink-inputs | while read line; do
        # Update current sink input id 
        [[ $line =~ ^Sink\ Input\ \#([[:digit:]]+) ]] && this_input=${BASH_REMATCH[1]}
        # check if it is spotify
        if [[ $line =~ "application.name = \"spotify\"" ]]; then
                echo "Spotify is sink-input ${this_input}"
                case $1 in
                  volume)
                                pactl set-sink-input-volume ${this_input} $2
                                ;;
                        up) 
                                pactl set-sink-input-volume ${this_input} +5%
                                ;;
                        down)
                                pactl set-sink-input-volume ${this_input} -5%
                                ;;
                        mute)
                                pactl set-sink-input-mute ${this_input} toggle
                                ;;
                        *)
                                echo "Error"
                                ;;
                esac
        fi
 
done
